# -*- coding: utf-8 -*-
'''
    Author: smallmi
    Blog: http://www.smallmi.com
'''
"""
Django settings for omms project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
import ldap
from django_auth_ldap.config import LDAPSearch

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))

PROJECT_DIR = os.path.dirname(BASE_DIR)
LOG_DIR = os.path.join(PROJECT_DIR, 'logs')
OMMS_LOG_FILE = os.path.join(LOG_DIR, 'omms.log')
ANSIBLE_LOG_FILE = os.path.join(LOG_DIR, 'ansible.log')
LOG_LEVEL = 'DEBUG'

if not os.path.isdir(LOG_DIR):
    os.makedirs(LOG_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8=t&=8ozvlnr9d^n+b=^y*o188fps%5wj@p^gopbloyi8@gh)8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = "accounts.User"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'accounts',
    'accounts.templatetags',
    'dashboard',
    'cmdb',
    'tasks',
    'release',
    'monitor',
    'kube',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'breadcrumbs.middleware.BreadcrumbsMiddleware',
]

WEBSOCKET_FACTORY_CLASS = 'controller.dwebsocket.backends.default.factory.WebSocketFactory'
# MIDDLEWARE_CLASSES = [
#     'controller.dwebsocket.middleware.WebSocketMiddleware',
# ]


ROOT_URLCONF = 'omms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
            ],
        },
    },
]

WSGI_APPLICATION = 'omms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'omms',
        'USER': 'root',
        'PASSWORD': 'Dfjr@2017!~',
        'HOST': '192.168.201.53',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', storage_engine='MyISAM'",
            'charset': 'utf8',
        },
    }
}


# ladp的地址和端口号
AUTH_LDAP_SERVER_URI = "ldap://192.168.201.74:389"

LDAP_DOMAIN = "@oriental-finance.com"

AUTH_LDAP_USER_SEARCH = LDAPSearch("DC=oriental-finance,DC=com", ldap.SCOPE_SUBTREE,
                                   "(&(objectClass=person)(sAMAccountName=%(user)s))")


AUTHENTICATION_BACKENDS = (

    "django_auth_ldap.backend.LDAPBackend",

    "django.contrib.auth.backends.ModelBackend",

)


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Logging setting
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'main': {
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'format': '%(asctime)s [%(module)s %(levelname)s] %(message)s',
        },
        'simple': {
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'format': '[%(asctime)s] [%(levelname)s] %(message)s',
        },
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'main'
        },
        'file': {
            'encoding': 'utf8',
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': 1024*1024*100,
            'backupCount': 7,
            'formatter': 'main',
            'filename': OMMS_LOG_FILE,
        },
        'ansible_logs': {
            'encoding': 'utf8',
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'simple',
            'filename': ANSIBLE_LOG_FILE,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['null'],
            'propagate': False,
            'level': LOG_LEVEL,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'omms': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
        },
        'omms.users.api': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
        },
        'omms.users.view': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
        },
        'ansible_api': {
            'handlers': ['console', 'ansible_logs'],
            'level': LOG_LEVEL,
        },
        'django_auth_ldap': {
            'handlers': ['console', 'file'],
            'level': "INFO",
        },
        # 'django.db': {
        #     'handlers': ['console', 'file'],
        #     'level': 'DEBUG'
        # }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

LOGIN_URL = '/accounts/login/'
MEDIA_ROOT = 'uploads/'
MEDIA_URL = 'uploads/'

BREADCRUMBS_AUTO_HOME: True
BREADCRUMBS_HOME_TITLE: u'Home'

EMAIL_USE_TLS = False
EMAIL_HOST = 'smtp.mxhichina.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'ops@smallmi.com'
EMAIL_HOST_PASSWORD = '0ps@1234'
DEFAULT_FROM_EMAIL = 'Paleluan FMS<ops@smallmi.com>'
# 要细分统计的故障类型ID
SPECIAL_TYPES = [7, 8]

# 邮件连接地址
EMAIL_DOMAIN_LINK = 'http://pfms.smallmi.com'

# JAVA 环境变量
JAVA_PATH = '/oriental/java/bin'

# MAVEN 环境变量
MAVEN_BIN = '/tools/apache-maven/bin/mvn'

# JAR文件上传路径
JAR_UPLOAD_PATH = '/oriental/jar/'

# git代码路径
GIT_WORKSPACE = '/tmp/workspace/'
